<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>LughSharp</Title>
        <AssemblyName>LughSharp</AssemblyName>
        <RootNamespace>LughSharp</RootNamespace>
        <Authors>Richard Ikin</Authors>
        <Version>0.1.0</Version>
        <Description>C# 2D/3D Game Framework.</Description>
        <RepositoryUrl>https://github.com/biffbaff64/LughSharp</RepositoryUrl>
        <LangVersion>latestmajor</LangVersion>
        <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
        <IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
        <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
        <AssemblyVersion>0.0.0.1</AssemblyVersion>
        <FileVersion>0.0.0.1</FileVersion>
        <PackageTags>CSharp;2D;Framework;OpenGL;</PackageTags>
        <PackageReleaseNotes>Release v0.1.0 for use with my game project. This will most likely still have issues and they will be fixed along the way</PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/biffbaff64/LughSharpFramework</PackageProjectUrl>
        <!--        <PackageIcon>lughicon.png</PackageIcon>-->
        <Copyright>Copyright 2024 Circa64 Software Projects</Copyright>
        <Company>Circa64 Software Projects</Company>
        <UserSecretsId>15077a63-55d3-46e9-b882-0b5cf985e7cc</UserSecretsId>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsWindows)'=='true'">
        <DefineConstants>Windows</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(IsOSX)'=='true'">
        <DefineConstants>OSX</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(IsLinux)'=='true'">
        <DefineConstants>Linux</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Release|AnyCPU'">
        <Optimize>True</Optimize>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug|Release|AnyCPU'">
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|Release|AnyCPU'">
        <OutputPath>$(SolutionDir)bin\$(Configuration)\$(TargetFramework)\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotGLFW" Version="1.2.0"/>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="RestSharp" Version="114.0.0" />
        <PackageReference Include="SharpZipLib" Version="1.4.2" />
        <PackageReference Include="SixLabors.ImageSharp" Version="4.0.0" />
        <PackageReference Include="StbiSharp" Version="1.2.1"/>
        <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
        <PackageReference Include="System.Drawing.Primitives" Version="4.3.0"/>
        <PackageReference Include="System.IO.Abstractions" Version="22.1.1" />
        <PackageReference Include="System.IO.Hashing" Version="10.0.9" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2"/>
        <PackageReference Include="System.Text.Json" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Assets\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="lib\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="runtimes\**\*.*">
            <Pack>true</Pack>
            <PackagePath>runtimes</PackagePath>
        </Content>
    </ItemGroup>
</Project>
