// /////////////////////////////////////////////////////////////////////////////
//  MIT License
// 
//  Copyright (c) 2024 Circa64 Software Projects / Richard Ikin.
// 
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
// 
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// /////////////////////////////////////////////////////////////////////////////

using System.Diagnostics.CodeAnalysis;

using JetBrains.Annotations;

namespace LughSharp.Core.Graphics.OpenGL;

/// <summary>
/// OpenGL functions.
/// </summary>
[PublicAPI]
[SuppressMessage( "ReSharper", "InconsistentNaming" )]
public partial interface IGL
{
    [PublicAPI]
    enum Format
    {
        Alpha          = GLAlpha,
        RGB            = GLRGB,
        RGBA           = GLRGBA,
        RGBA4          = GLRGB4,
        RGB565         = GLRGB565,
        Luminance      = GLLuminance,
        LuminanceAlpha = GLLuminanceAlpha,
        ColorIndex     = GLColorIndex
    }

    // ========================================================================
    // ========================================================================

    const int GLContextCoreProfileBit                               = 0x00000001;
    const int GLContextCompatibilityProfileBit                      = 0x00000002;
    const int GLContextFlagNoErrorBit                               = 0x00000008;
    const int GLAccumBufferBit                                      = 0x00000200;
    const int GLClientMappedBufferBarrierBit                        = 0x00004000;
    const int GLQueryBufferBarrierBit                               = 0x00008000;
    const int GLContextFlagForwardCompatibleBit                     = 0x0001;
    const int GLMapPersistentBit                                    = 0x0040;
    const int GLMapCoherentBit                                      = 0x0080;
    const int GLDynamicStorageBit                                   = 0x0100;
    const int GLClientStorageBit                                    = 0x0200;
    const int GLFrontLeft                                           = 0x0400;
    const int GLFrontRight                                          = 0x0401;
    const int GLBackLeft                                            = 0x0402;
    const int GLBackRight                                           = 0x0403;
    const int GLLeft                                                = 0x0406;
    const int GLRight                                               = 0x0407;
    const int GLPointSize                                           = 0x0B11;
    const int GLSmoothPointSizeRange                                = 0x0B12;
    const int GLSmoothPointSizeGranularity                          = 0x0B13;
    const int GLLineSmooth                                          = 0x0B20;
    const int GLSmoothLineWidthRange                                = 0x0B22;
    const int GLSmoothLineWidthGranularity                          = 0x0B23;
    const int GLPolygonMode                                         = 0x0B40;
    const int GLPolygonSmooth                                       = 0x0B41;
    const int GLLighting                                            = 0x0B50;
    const int GLColorMaterial                                       = 0x0B57;
    const int GLFog                                                 = 0x0B60;
    const int GLTextureCoordArray                                   = 0x0B78;
    const int GLBlendDst                                            = 0x0BE0;
    const int GLBlendSrc                                            = 0x0BE1;
    const int GLLogicOpMode                                         = 0x0BF0;
    const int GLColorLogicOp                                        = 0x0BF2;
    const int GLNormalArray                                         = 0x8075;
    const int GLNormalize                                           = 0x0BA1;
    const int GLDrawBuffer                                          = 0x0C01;
    const int GLDoublebuffer                                        = 0x0C32;
    const int GLStereo                                              = 0x0C33;
    const int GLLineSmoothHint                                      = 0x0C52;
    const int GLPolygonSmoothHint                                   = 0x0C53;
    const int GLUnpackSwapBytes                                     = 0x0CF0;
    const int GLUnpackLsbFirst                                      = 0x0CF1;
    const int GLPackSwapBytes                                       = 0x0D00;
    const int GLPackLsbFirst                                        = 0x0D01;
    const int GLMaxClipDistances                                    = 0x0D32;
    const int GLTexture1D                                           = 0x0DE0;
    const int GLTextureTarget                                       = 0x1006;
    const int GLDouble                                              = 0x140A;
    const int GLClear                                               = 0x1500;
    const int GLAnd                                                 = 0x1501;
    const int GLAndReverse                                          = 0x1502;
    const int GLCopy                                                = 0x1503;
    const int GLAndInverted                                         = 0x1504;
    const int GLNoop                                                = 0x1505;
    const int GLXor                                                 = 0x1506;
    const int GLOr                                                  = 0x1507;
    const int GLNor                                                 = 0x1508;
    const int GLEquiv                                               = 0x1509;
    const int GLOrReverse                                           = 0x150B;
    const int GLCopyInverted                                        = 0x150C;
    const int GLOrInverted                                          = 0x150D;
    const int GLNand                                                = 0x150E;
    const int GLSet                                                 = 0x150F;
    const int GLModelview                                           = 0x1700;
    const int GLProjection                                          = 0x1701;
    const int GLPoint                                               = 0x1B00;
    const int GLLine                                                = 0x1B01;
    const int GLFill                                                = 0x1B02;
    const int GLPolygonOffsetPoint                                  = 0x2A01;
    const int GLPolygonOffsetLine                                   = 0x2A02;
    const int GLR3G3B2                                              = 0x2A10;
    const int GLClipDistance0                                       = 0x3000;
    const int GLClipDistance1                                       = 0x3001;
    const int GLClipDistance2                                       = 0x3002;
    const int GLClipDistance3                                       = 0x3003;
    const int GLClipDistance4                                       = 0x3004;
    const int GLClipDistance5                                       = 0x3005;
    const int GLClipDistance6                                       = 0x3006;
    const int GLClipDistance7                                       = 0x3007;
    const int GLColorArray                                          = 0x8076;
    const int GLR16F                                                = 0x822D;
    const int GLR32F                                                = 0x822E;
    const int GLRg16F                                               = 0x822F;
    const int GLRg32F                                               = 0x8230;
    const int GLR8I                                                 = 0x8231;
    const int GLR8UI                                                = 0x8232;
    const int GLR16I                                                = 0x8233;
    const int GLR16UI                                               = 0x8234;
    const int GLR32I                                                = 0x8235;
    const int GLR32UI                                               = 0x8236;
    const int GLRg8I                                                = 0x8237;
    const int GLRg8UI                                               = 0x8238;
    const int GLRg16I                                               = 0x8239;
    const int GLRg16UI                                              = 0x823A;
    const int GLRg32I                                               = 0x823B;
    const int GLRg32UI                                              = 0x823C;
    const int GLVertexArrayBufferBinding                            = 0x8896;
    const int GLNormalArrayBufferBinding                            = 0x8897;
    const int GLColorArrayBufferBinding                             = 0x8898;
    const int GLTextureCoordArrayBufferBinding                      = 0x889A;
    const int GLMaxTextureCoords                                    = 0x8871;
    const int GLRGBA32F                                             = 0x8814;
    const int GLRGB32F                                              = 0x8815;
    const int GLRGBA16F                                             = 0x881A;
    const int GLRGB16F                                              = 0x881B;
    const int GLFloatMat2X3                                         = 0x8B65;
    const int GLFloatMat2X4                                         = 0x8B66;
    const int GLFloatMat3X2                                         = 0x8B67;
    const int GLFloatMat3X4                                         = 0x8B68;
    const int GLFloatMat4X2                                         = 0x8B69;
    const int GLFloatMat4X3                                         = 0x8B6A;
    const int GLR11FG11FB10F                                        = 0x8C3A;
    const int GLUnsignedInt10F11F11FRev                             = 0x8C3B;
    const int GLDepthComponent32F                                   = 0x8CAC;
    const int GLDepth32FStencil8                                    = 0x8CAD;
    const int GLRGBA32UI                                            = 0x8D70;
    const int GLRGB32UI                                             = 0x8D71;
    const int GLRGBA16UI                                            = 0x8D76;
    const int GLRGB16UI                                             = 0x8D77;
    const int GLRGBA8UI                                             = 0x8D7C;
    const int GLRGB8UI                                              = 0x8D7D;
    const int GLRGBA32I                                             = 0x8D82;
    const int GLRGB32I                                              = 0x8D83;
    const int GLRGBA16I                                             = 0x8D88;
    const int GLRGB16I                                              = 0x8D89;
    const int GLRGBA8I                                              = 0x8D8E;
    const int GLRGB8I                                               = 0x8D8F;
    const int GLTextureBinding1D                                    = 0x8068;
    const int GLProxyTexture1D                                      = 0x8063;
    const int GLProxyTexture2D                                      = 0x8064;
    const int GLRGB4                                                = 0x804F;
    const int GLRGB5                                                = 0x8050;
    const int GLRGB10                                               = 0x8052;
    const int GLRGB12                                               = 0x8053;
    const int GLRGB16                                               = 0x8054;
    const int GLRGBA2                                               = 0x8055;
    const int GLRGBA12                                              = 0x805A;
    const int GLRGBA16                                              = 0x805B;
    const int GLUnsignedByte332                                     = 0x8032;
    const int GLUnsignedInt8888                                     = 0x8035;
    const int GLUnsignedInt1010102                                  = 0x8036;
    const int GLPackSkipImages                                      = 0x806B;
    const int GLPackImageHeight                                     = 0x806C;
    const int GLProxyTexture3D                                      = 0x8070;
    const int GLBgr                                                 = 0x80E0;
    const int GLBgra                                                = 0x80E1;
    const int GLUnsignedByte233Rev                                  = 0x8362;
    const int GLUnsignedShort565Rev                                 = 0x8364;
    const int GLUnsignedShort4444Rev                                = 0x8365;
    const int GLUnsignedShort1555Rev                                = 0x8366;
    const int GLUnsignedInt8888Rev                                  = 0x8367;
    const int GLMultisample                                         = 0x809D;
    const int GLSampleAlphaToOne                                    = 0x809F;
    const int GLProxyTextureCubeMap                                 = 0x851B;
    const int GLCompressedRGB                                       = 0x84ED;
    const int GLCompressedRGBA                                      = 0x84EE;
    const int GLTextureCompressionHint                              = 0x84EF;
    const int GLTextureCompressedImageSize                          = 0x86A0;
    const int GLPointFadeThresholdSize                              = 0x8128;
    const int GLDepthComponent32                                    = 0x81A7;
    const int GLTextureLodBias                                      = 0x8501;
    const int GLQueryCounterBits                                    = 0x8864;
    const int GLBufferAccess                                        = 0x88BB;
    const int GLSamplesPassed                                       = 0x8914;
    const int GLSrc1Alpha                                           = 0x8589;
    const int GLMaxVaryingFloats                                    = 0x8B4B;
    const int GLSampler1D                                           = 0x8B5D;
    const int GLSampler1DShadow                                     = 0x8B61;
    const int GLPointSpriteCoordOrigin                              = 0x8CA0;
    const int GLLowerLeft                                           = 0x8CA1;
    const int GLUpperLeft                                           = 0x8CA2;
    const int GLSrgbAlpha                                           = 0x8C42;
    const int GLCompressedSrgb                                      = 0x8C48;
    const int GLCompressedSrgbAlpha                                 = 0x8C49;
    const int GLCompressedRed                                       = 0x8225;
    const int GLCompressedRg                                        = 0x8226;
    const int GLClampReadColor                                      = 0x891C;
    const int GLFixedOnly                                           = 0x891D;
    const int GLTexture1DArray                                      = 0x8C18;
    const int GLProxyTexture1DArray                                 = 0x8C19;
    const int GLProxyTexture2DArray                                 = 0x8C1B;
    const int GLTextureBinding1DArray                               = 0x8C1C;
    const int GLGreenInteger                                        = 0x8D95;
    const int GLBlueInteger                                         = 0x8D96;
    const int GLBgrInteger                                          = 0x8D9A;
    const int GLBgraInteger                                         = 0x8D9B;
    const int GLSampler1DArray                                      = 0x8DC0;
    const int GLSampler1DArrayShadow                                = 0x8DC3;
    const int GLIntSampler1D                                        = 0x8DC9;
    const int GLIntSampler1DArray                                   = 0x8DCE;
    const int GLUnsignedIntSampler1D                                = 0x8DD1;
    const int GLUnsignedIntSampler1DArray                           = 0x8DD6;
    const int GLQueryWait                                           = 0x8E13;
    const int GLQueryNoWait                                         = 0x8E14;
    const int GLQueryByRegionWait                                   = 0x8E15;
    const int GLQueryByRegionNoWait                                 = 0x8E16;
    const int GLFramebufferIncompleteDrawBuffer                     = 0x8CDB;
    const int GLFramebufferIncompleteReadBuffer                     = 0x8CDC;
    const int GLColorAttachment16                                   = 0x8CF0;
    const int GLColorAttachment17                                   = 0x8CF1;
    const int GLColorAttachment18                                   = 0x8CF2;
    const int GLColorAttachment19                                   = 0x8CF3;
    const int GLColorAttachment20                                   = 0x8CF4;
    const int GLColorAttachment21                                   = 0x8CF5;
    const int GLColorAttachment22                                   = 0x8CF6;
    const int GLColorAttachment23                                   = 0x8CF7;
    const int GLColorAttachment24                                   = 0x8CF8;
    const int GLColorAttachment25                                   = 0x8CF9;
    const int GLColorAttachment26                                   = 0x8CFA;
    const int GLColorAttachment27                                   = 0x8CFB;
    const int GLColorAttachment28                                   = 0x8CFC;
    const int GLColorAttachment29                                   = 0x8CFD;
    const int GLColorAttachment30                                   = 0x8CFE;
    const int GLColorAttachment31                                   = 0x8CFF;
    const int GLStencilIndex1                                       = 0x8D46;
    const int GLStencilIndex4                                       = 0x8D47;
    const int GLStencilIndex16                                      = 0x8D49;
    const int GLFramebufferSrgb                                     = 0x8DB9;
    const int GLCompressedRedRGTC1                                  = 0x8DBB;
    const int GLCompressedSignedRedRGTC1                            = 0x8DBC;
    const int GLCompressedRgRGTC2                                   = 0x8DBD;
    const int GLCompressedSignedRgRGTC2                             = 0x8DBE;
    const int GLR16                                                 = 0x822A;
    const int GLRg16                                                = 0x822C;
    const int GLSampler2DRect                                       = 0x8B63;
    const int GLSampler2DRectShadow                                 = 0x8B64;
    const int GLIntSampler2DRect                                    = 0x8DCD;
    const int GLUnsignedIntSampler2DRect                            = 0x8DD5;
    const int GLTextureRectangle                                    = 0x84F5;
    const int GLTextureBindingRectangle                             = 0x84F6;
    const int GLProxyTextureRectangle                               = 0x84F7;
    const int GLMaxRectangleTextureSize                             = 0x84F8;
    const int GLR16Snorm                                            = 0x8F98;
    const int GLRg16Snorm                                           = 0x8F99;
    const int GLRGB16Snorm                                          = 0x8F9A;
    const int GLRGBA16Snorm                                         = 0x8F9B;
    const int GLPrimitiveRestart                                    = 0x8F9D;
    const int GLPrimitiveRestartIndex                               = 0x8F9E;
    const int GLUniformBlockReferencedByGeometryShader              = 0x8A45;
    const int GLProgramPointSize                                    = 0x8642;
    const int GLDepthClamp                                          = 0x864F;
    const int GLQuadsFollowProvokingVertexConvention                = 0x8E4C;
    const int GLProvokingVertex                                     = 0x8E4F;
    const int GLTextureCubeMapSeamless                              = 0x884F;
    const int GLSrc1Color                                           = 0x88F9;
    const int GLOneMinusSrc1Color                                   = 0x88FA;
    const int GLOneMinusSrc1Alpha                                   = 0x88FB;
    const int GLMaxDualSourceDrawBuffers                            = 0x88FC;
    const int GLTextureSwizzleRGBA                                  = 0x8E46;
    const int GLTimeElapsed                                         = 0x88BF;
    const int GLTimestamp                                           = 0x8E28;
    const int GLMaxVertexStreams                                    = 0x8E71;
    const int GLDoubleVec2                                          = 0x8FFC;
    const int GLDoubleVec3                                          = 0x8FFD;
    const int GLDoubleVec4                                          = 0x8FFE;
    const int GLDoubleMat2                                          = 0x8F46;
    const int GLDoubleMat3                                          = 0x8F47;
    const int GLDoubleMat4                                          = 0x8F48;
    const int GLDoubleMat2X3                                        = 0x8F49;
    const int GLDoubleMat2X4                                        = 0x8F4A;
    const int GLDoubleMat3X2                                        = 0x8F4B;
    const int GLDoubleMat3X4                                        = 0x8F4C;
    const int GLDoubleMat4X2                                        = 0x8F4D;
    const int GLDoubleMat4X3                                        = 0x8F4E;
    const int GLActiveSubroutines                                   = 0x8DE5;
    const int GLActiveSubroutineUniforms                            = 0x8DE6;
    const int GLActiveSubroutineUniformLocations                    = 0x8E47;
    const int GLActiveSubroutineMaxLength                           = 0x8E48;
    const int GLActiveSubroutineUniformMaxLength                    = 0x8E49;
    const int GLMaxSubroutines                                      = 0x8DE7;
    const int GLMaxSubroutineUniformLocations                       = 0x8DE8;
    const int GLNumCompatibleSubroutines                            = 0x8E4A;
    const int GLCompatibleSubroutines                               = 0x8E4B;
    const int GLPatchDefaultInnerLevel                              = 0x8E73;
    const int GLPatchDefaultOuterLevel                              = 0x8E74;
    const int GLUniformBlockReferencedByTessControlShader           = 0x84F0;
    const int GLUniformBlockReferencedByTessEvaluationShader        = 0x84F1;
    const int GLTransformFeedbackBufferPaused                       = 0x8E23;
    const int GLTransformFeedbackBufferActive                       = 0x8E24;
    const int GLMaxTransformFeedbackBuffers                         = 0x8E70;
    const int GLMaxViewports                                        = 0x825B;
    const int GLViewportSubpixelBits                                = 0x825C;
    const int GLViewportBoundsRange                                 = 0x825D;
    const int GLViewportIndexProvokingVertex                        = 0x825F;
    const int GLMaxCombinedImageUnitsAndFragmentOutputs             = 0x8F39;
    const int GLCompressedRGBABPTCUnorm                             = 0x8E8C;
    const int GLCompressedSrgbAlphaBPTCUnorm                        = 0x8E8D;
    const int GLCompressedRGBBPTCSignedFloat                        = 0x8E8E;
    const int GLCompressedRGBBPTCUnsignedFloat                      = 0x8E8F;
    const int GLNumShadingLanguageVersions                          = 0x82E9;
    const int GLVertexAttribArrayLong                               = 0x874E;
    const int GLInternalformatSupported                             = 0x826F;
    const int GLInternalformatPreferred                             = 0x8270;
    const int GLInternalformatRedSize                               = 0x8271;
    const int GLInternalformatGreenSize                             = 0x8272;
    const int GLInternalformatBlueSize                              = 0x8273;
    const int GLInternalformatAlphaSize                             = 0x8274;
    const int GLInternalformatDepthSize                             = 0x8275;
    const int GLInternalformatStencilSize                           = 0x8276;
    const int GLInternalformatSharedSize                            = 0x8277;
    const int GLInternalformatRedType                               = 0x8278;
    const int GLInternalformatGreenType                             = 0x8279;
    const int GLInternalformatBlueType                              = 0x827A;
    const int GLInternalformatAlphaType                             = 0x827B;
    const int GLInternalformatDepthType                             = 0x827C;
    const int GLInternalformatStencilType                           = 0x827D;
    const int GLMaxWidth                                            = 0x827E;
    const int GLMaxHeight                                           = 0x827F;
    const int GLMaxDepth                                            = 0x8280;
    const int GLMaxLayers                                           = 0x8281;
    const int GLMaxCombinedDimensions                               = 0x8282;
    const int GLColorComponents                                     = 0x8283;
    const int GLDepthComponents                                     = 0x8284;
    const int GLStencilComponents                                   = 0x8285;
    const int GLColorRenderable                                     = 0x8286;
    const int GLDepthRenderable                                     = 0x8287;
    const int GLStencilRenderable                                   = 0x8288;
    const int GLFramebufferRenderable                               = 0x8289;
    const int GLFramebufferRenderableLayered                        = 0x828A;
    const int GLFramebufferBlend                                    = 0x828B;
    const int GLReadPixels                                          = 0x828C;
    const int GLReadPixelsFormat                                    = 0x828D;
    const int GLReadPixelsType                                      = 0x828E;
    const int GLTextureImageFormat                                  = 0x828F;
    const int GLTextureImageType                                    = 0x8290;
    const int GLGetTextureImageFormat                               = 0x8291;
    const int GLGetTextureImageType                                 = 0x8292;
    const int GLMipmap                                              = 0x8293;
    const int GLManualGenerateMipmap                                = 0x8294;
    const int GLAutoGenerateMipmap                                  = 0x8295;
    const int GLColorEncoding                                       = 0x8296;
    const int GLSrgbRead                                            = 0x8297;
    const int GLSrgbWrite                                           = 0x8298;
    const int GLFilter                                              = 0x829A;
    const int GLVertexTexture                                       = 0x829B;
    const int GLTessControlTexture                                  = 0x829C;
    const int GLTessEvaluationTexture                               = 0x829D;
    const int GLGeometryTexture                                     = 0x829E;
    const int GLFragmentTexture                                     = 0x829F;
    const int GLComputeTexture                                      = 0x82A0;
    const int GLTextureShadow                                       = 0x82A1;
    const int GLTextureGather                                       = 0x82A2;
    const int GLTextureGatherShadow                                 = 0x82A3;
    const int GLShaderImageLoad                                     = 0x82A4;
    const int GLShaderImageStore                                    = 0x82A5;
    const int GLShaderImageAtomic                                   = 0x82A6;
    const int GLImageTexelSize                                      = 0x82A7;
    const int GLImageCompatibilityClass                             = 0x82A8;
    const int GLImagePixelFormat                                    = 0x82A9;
    const int GLImagePixelType                                      = 0x82AA;
    const int GLSimultaneousTextureAndDepthTest                     = 0x82AC;
    const int GLSimultaneousTextureAndStencilTest                   = 0x82AD;
    const int GLSimultaneousTextureAndDepthWrite                    = 0x82AE;
    const int GLSimultaneousTextureAndStencilWrite                  = 0x82AF;
    const int GLTextureCompressedBlockWidth                         = 0x82B1;
    const int GLTextureCompressedBlockHeight                        = 0x82B2;
    const int GLTextureCompressedBlockSize                          = 0x82B3;
    const int GLClearBuffer                                         = 0x82B4;
    const int GLTextureView                                         = 0x82B5;
    const int GLViewCompatibilityClass                              = 0x82B6;
    const int GLFullSupport                                         = 0x82B7;
    const int GLCaveatSupport                                       = 0x82B8;
    const int GLImageClass4X32                                      = 0x82B9;
    const int GLImageClass2X32                                      = 0x82BA;
    const int GLImageClass1X32                                      = 0x82BB;
    const int GLImageClass4X16                                      = 0x82BC;
    const int GLImageClass2X16                                      = 0x82BD;
    const int GLImageClass1X16                                      = 0x82BE;
    const int GLImageClass4X8                                       = 0x82BF;
    const int GLImageClass2X8                                       = 0x82C0;
    const int GLImageClass1X8                                       = 0x82C1;
    const int GLImageClass111110                                    = 0x82C2;
    const int GLImageClass1010102                                   = 0x82C3;
    const int GLViewClass128Bits                                    = 0x82C4;
    const int GLViewClass96Bits                                     = 0x82C5;
    const int GLViewClass64Bits                                     = 0x82C6;
    const int GLViewClass48Bits                                     = 0x82C7;
    const int GLViewClass32Bits                                     = 0x82C8;
    const int GLViewClass24Bits                                     = 0x82C9;
    const int GLViewClass16Bits                                     = 0x82CA;
    const int GLViewClass8Bits                                      = 0x82CB;
    const int GLViewClassS3TCDxt1RGB                                = 0x82CC;
    const int GLViewClassS3TCDxt1RGBA                               = 0x82CD;
    const int GLViewClassS3TCDxt3RGBA                               = 0x82CE;
    const int GLViewClassS3TCDxt5RGBA                               = 0x82CF;
    const int GLViewClassRGTC1Red                                   = 0x82D0;
    const int GLViewClassRGTC2Rg                                    = 0x82D1;
    const int GLViewClassBPTCUnorm                                  = 0x82D2;
    const int GLViewClassBPTCFloat                                  = 0x82D3;
    const int GLTextureViewMinLevel                                 = 0x82DB;
    const int GLTextureViewNumLevels                                = 0x82DC;
    const int GLTextureViewMinLayer                                 = 0x82DD;
    const int GLTextureViewNumLayers                                = 0x82DE;
    const int GLBufferImmutableStorage                              = 0x821F;
    const int GLBufferStorageFlags                                  = 0x8220;
    const int GLMirrorClampToEdge                                   = 0x8743;
    const int GLQueryWaitInverted                                   = 0x8E17;
    const int GLQueryNoWaitInverted                                 = 0x8E18;
    const int GLQueryByRegionWaitInverted                           = 0x8E19;
    const int GLQueryByRegionNoWaitInverted                         = 0x8E1A;
    const int GLMaxCullDistances                                    = 0x82F9;
    const int GLMaxCombinedClipAndCullDistances                     = 0x82FA;
    const int GLQueryTarget                                         = 0x82EA;
    const int GLContextReleaseBehavior                              = 0x82FB;
    const int GLContextReleaseBehaviorFlush                         = 0x82FC;
    const int GLParameterBuffer                                     = 0x80EE;
    const int GLParameterBufferBinding                              = 0x80EF;
    const int GLVerticesSubmitted                                   = 0x82EE;
    const int GLPrimitivesSubmitted                                 = 0x82EF;
    const int GLVertexShaderInvocations                             = 0x82F0;
    const int GLTessControlShaderPatches                            = 0x82F1;
    const int GLTessEvaluationShaderInvocations                     = 0x82F2;
    const int GLGeometryShaderPrimitivesEmitted                     = 0x82F3;
    const int GLFragmentShaderInvocations                           = 0x82F4;
    const int GLComputeShaderInvocations                            = 0x82F5;
    const int GLClippingInputPrimitives                             = 0x82F6;
    const int GLClippingOutputPrimitives                            = 0x82F7;
    const int GLPolygonOffsetClamp                                  = 0x8E1B;
    const int GLTextureMaxAnisotropy                                = 0x84FE;
    const int GLMaxTextureMaxAnisotropy                             = 0x84FF;
    const int GLTransformFeedbackOverflow                           = 0x82EC;
    const int GLTransformFeedbackStreamOverflow                     = 0x82ED;
    const int GLContextProfileMask                                  = 0x9126;
    const int GLProxyTexture2DMultisample                           = 0x9101;
    const int GLProxyTexture2DMultisampleArray                      = 0x9103;
    const int GLProxyTextureCubeMapArray                            = 0x900B;
    const int GLImage1D                                             = 0x904C;
    const int GLImage2DRect                                         = 0x904F;
    const int GLImage1DArray                                        = 0x9052;
    const int GLImage2DMultisample                                  = 0x9055;
    const int GLImage2DMultisampleArray                             = 0x9056;
    const int GLIntImage1D                                          = 0x9057;
    const int GLIntImage2DRect                                      = 0x905A;
    const int GLIntImage1DArray                                     = 0x905D;
    const int GLIntImage2DMultisample                               = 0x9060;
    const int GLIntImage2DMultisampleArray                          = 0x9061;
    const int GLUnsignedIntImage1D                                  = 0x9062;
    const int GLUnsignedIntImage2DRect                              = 0x9065;
    const int GLUnsignedIntImage1DArray                             = 0x9068;
    const int GLUnsignedIntImage2DMultisample                       = 0x906B;
    const int GLUnsignedIntImage2DMultisampleArray                  = 0x906C;
    const int GLMaxImageSamples                                     = 0x906D;
    const int GLUniformBlockReferencedByComputeShader               = 0x90EC;
    const int GLAtomicCounterBufferReferencedByComputeShader        = 0x90ED;
    const int GLVertexSubroutine                                    = 0x92E8;
    const int GLTessControlSubroutine                               = 0x92E9;
    const int GLTessEvaluationSubroutine                            = 0x92EA;
    const int GLGeometrySubroutine                                  = 0x92EB;
    const int GLFragmentSubroutine                                  = 0x92EC;
    const int GLComputeSubroutine                                   = 0x92ED;
    const int GLVertexSubroutineUniform                             = 0x92EE;
    const int GLTessControlSubroutineUniform                        = 0x92EF;
    const int GLTessEvaluationSubroutineUniform                     = 0x92F0;
    const int GLGeometrySubroutineUniform                           = 0x92F1;
    const int GLFragmentSubroutineUniform                           = 0x92F2;
    const int GLComputeSubroutineUniform                            = 0x92F3;
    const int GLMaxNumCompatibleSubroutines                         = 0x92F8;
    const int GLLocationIndex                                       = 0x930F;
    const int GLClearTexture                                        = 0x9365;
    const int GLLocationComponent                                   = 0x934A;
    const int GLTransformFeedbackBufferIndex                        = 0x934B;
    const int GLTransformFeedbackBufferStride                       = 0x934C;
    const int GLQueryBuffer                                         = 0x9192;
    const int GLQueryBufferBinding                                  = 0x9193;
    const int GLQueryResultNoWait                                   = 0x9194;
    const int GLNegativeOneToOne                                    = 0x935E;
    const int GLZeroToOne                                           = 0x935F;
    const int GLClipOrigin                                          = 0x935C;
    const int GLClipDepthMode                                       = 0x935D;
    const int GLRGB10A2UI                                           = 0x906F;
    const int GLSpirVExtensions                                     = 0x9553;
    const int GLNumSpirVExtensions                                  = 0x9554;
    const int GLShaderBinaryFormatSpirV                             = 0x9551;
    const int GLSpirVBinary                                         = 0x9552;
    const int GLUnpackCompressedBlockWidth                          = 0x9127;
    const int GLUnpackCompressedBlockHeight                         = 0x9128;
    const int GLUnpackCompressedBlockDepth                          = 0x9129;
    const int GLUnpackCompressedBlockSize                           = 0x912A;
    const int GLPackCompressedBlockWidth                            = 0x912B;
    const int GLPackCompressedBlockHeight                           = 0x912C;
    const int GLPackCompressedBlockDepth                            = 0x912D;
    const int GLPackCompressedBlockSize                             = 0x912E;
    const int GLMinMapBufferAlignment                               = 0x90BC;
    const int GLAtomicCounterBufferDataSize                         = 0x92C4;
    const int GLAtomicCounterBufferActiveAtomicCounters             = 0x92C5;
    const int GLAtomicCounterBufferActiveAtomicCounterIndices       = 0x92C6;
    const int GLAtomicCounterBufferReferencedByVertexShader         = 0x92C7;
    const int GLAtomicCounterBufferReferencedByTessControlShader    = 0x92C8;
    const int GLAtomicCounterBufferReferencedByTessEvaluationShader = 0x92C9;
    const int GLAtomicCounterBufferReferencedByGeometryShader       = 0x92CA;
    const int GLAtomicCounterBufferReferencedByFragmentShader       = 0x92CB;
    const int GLUniformAtomicCounterBufferIndex                     = 0x92DA;
}

// ============================================================================
// ============================================================================