// ///////////////////////////////////////////////////////////////////////////////
// MIT License
//
// Copyright (c) 2024 Circa64 Software Projects / Richard Ikin.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// ///////////////////////////////////////////////////////////////////////////////

using System.Diagnostics;

using LughSharp.Source.Collections;
using LughSharp.Source.Graphics.Fonts;
using LughSharp.Source.Graphics.G2D;
using LughSharp.Source.Scene2D.Listeners;
using LughSharp.Source.Scene2D.UI.Styles;
using LughSharp.Source.Scene2D.Utils;
using LughSharp.Source.Utils.Pooling;

namespace LughSharp.Source.Scene2D.UI;

/// A single-line text input field.
/// <para>
/// The preferred height of a text field is the height of the <see cref="BitmapFont"/>
/// and <see cref="TextFieldStyle.Background"/>. The preferred width of a text field is 150,
/// a relatively arbitrary size.
/// </para>
/// <para>
/// The text field will copy the currently selected text when ctrl+c is pressed, and
/// paste any text in the clipboard when ctrl+v is pressed. Clipboard functionality is
/// provided via the <see cref="IClipboard"/> interface.
/// </para>
/// <para>
/// The text field allows you to specify an <see cref="IOnScreenKeyboard"/> for displaying
/// a softkeyboard and piping all key events generated by the keyboard to the text field.
/// There are two standard implementations, one for the desktop and one for Android.
/// The desktop keyboard is a stub, as a softkeyboard is not needed on the desktop. The
/// Android <see cref="IOnScreenKeyboard"/> implementation will bring up the default IME.
/// </para>
[PublicAPI]
public class TextField : Widget, IStyleable< TextFieldStyle >
{
    public GlyphLayout         GlyphLayout              { get; set; } = new();
    public List< float >       GlyphPositions           { get; set; } = [ ];
    public ITextFieldFilter?   Filter                   { get; set; }
    public ITextFieldListener? Listener                 { get; set; }
    public string              Text                     { get; set; } = string.Empty;
    public string              MessageText              { get; set; } = string.Empty;
    public string              DisplayText              { get; set; } = string.Empty;
    public int                 Cursor                   { get; set; }
    public int                 SelectionStart           { get; set; }
    public int                 MaxLength                { get; set; }
    public bool                HasSelection             { get; set; }
    public bool                WriteEnters              { get; set; }
    public bool                FocusTraversal           { get; set; } = true;
    public bool                ProgrammaticChangeEvents { get; set; }
    public bool                Disabled                 { get; set; }
    public float               FontOffset               { get; set; }
    public float               TextHeight               { get; set; }
    public float               TextOffset               { get; set; }
    public float               KeyRepeatInitialTime     { get; private set; } = 0.4f;
    public float               KeyRepeatTime            { get; private set; } = 0.1f;

    // ========================================================================

    protected const char CarriageReturn = '\r';
    protected const char Newline        = '\n';
    protected const char Tab            = '\t';
    protected const char Backspace      = '\u0008';
    protected const char DeleteKey      = '\u007f';
    protected const char Bullet         = '\u0095';

    // ========================================================================

    private readonly bool                 _onlyFontChars = true;
    private readonly Align                _textAlign     = Align.Left;
    private readonly Vector2              _tmp1          = new();
    private readonly Vector2              _tmp2          = new();
    private readonly Vector2              _tmp3          = new();
    private readonly BlinkTaskManager     _blink;
    private readonly IClipboard?          _clipboard;
    private readonly KeyRepeatTaskManager _keyRepeat;

    private CancellationToken        _blinkCancellationToken;
    private Task?                    _blinkTask;
    private CancellationTokenSource? _blinkTokenSource;
    private bool                     _cursorOn;
    private bool                     _focused;
    private InputListener?           _inputListener;
    private IOnscreenKeyboard        _keyboard = new DefaultOnscreenKeyboard();
    private CancellationToken        _keyRepeatCancellationToken;
    private Task?                    _keyRepeatTask;
    private CancellationTokenSource? _keyRepeatTokenSource;
    private long                     _lastChangeTime;
    private StringBuilder?           _passwordBuffer;
    private char                     _passwordCharacter = Bullet;
    private bool                     _passwordMode;
    private float                    _renderOffset;
    private float                    _selectionWidth;
    private float                    _selectionX;
    private string?                  _undoText = string.Empty;
    private int                      _visibleTextEnd;
    private int                      _visibleTextStart;
    private TextFieldStyle           _style = null!;

    // ========================================================================

    /// <summary>
    /// Creates a new TextField object with the supplied text and <see cref="Skin"/>.
    /// </summary>
    /// <param name="text"> The text to display on the TextField. </param>
    /// <param name="skin"> The Skin holding the <see cref="TextFieldStyle"/>. </param>
    public TextField( string? text, Skin skin )
        : this( text, skin.Get< TextFieldStyle >() )
    {
    }

    /// <summary>
    /// Creates a new TextField object with the supplied text and <see cref="Skin"/>
    /// containing the names <see cref="TextFieldStyle"/>.
    /// </summary>
    /// <param name="text"> The text to display on the TextField. </param>
    /// <param name="skin"> The Skin holding the <see cref="TextFieldStyle"/>. </param>
    /// <param name="styleName"> The name of the TextFieldStyle to use. </param>
    public TextField( string? text, Skin skin, string styleName )
        : this( text, skin.Get< TextFieldStyle >( styleName ) )
    {
    }

    /// <summary>
    /// Creates a new TextField object with the supplied text and <see cref="TextFieldStyle"/>.
    /// </summary>
    /// <param name="text"> The text to display on the TextField. </param>
    /// <param name="style"> The <see cref="TextFieldStyle"/> to use. </param>
    public TextField( string? text, TextFieldStyle style )
    {
        _clipboard     = Engine.App.Clipboard;
        _blink         = new BlinkTaskManager( this );
        _keyRepeat     = new KeyRepeatTaskManager( this );
        _inputListener = new TextFieldClickListener( this );

        _blink.Create();
        _keyRepeat.Create();

        SetStyleSafe( style );
        SetText( text );
        SetSize( GetPrefWidthUnchecked(), GetPrefHeightUnchecked() );
    }

    /// <summary>
    /// If true, the text in this text field will be shown as bullet characters.
    /// <see cref="PasswordCharacter"/>
    /// </summary>
    public bool PasswordMode
    {
        get => _passwordMode;
        set
        {
            _passwordMode = value;
            UpdateDisplayText();
        }
    }

    /// <summary>
    /// The character to use for hiding the password, typically a bullet character but can
    /// be any character.
    /// </summary>
    public char PasswordCharacter
    {
        get => _passwordCharacter;
        set
        {
            _passwordCharacter = value;

            if ( PasswordMode )
            {
                UpdateDisplayText();
            }
        }
    }

    /// <inheritdoc />
    public override float GetPrefWidth()
    {
        return GetPrefWidthUnchecked();
    }

    /// <summary>
    /// The preferred width of the textfield based on the items it contains. This
    /// method is a wrapper for <see cref="GetPrefWidth()"/>, and is provided to
    /// allow calling safely from constructors.
    /// </summary>
    /// <returns> The preferred width of the textfield. </returns>
    protected float GetPrefWidthUnchecked()
    {
        return 150;
    }

    /// <inheritdoc />
    public override float GetPrefHeight()
    {
        return GetPrefHeightUnchecked();
    }

    /// <summary>
    /// The preferred height of the textfield based on the items it contains. This
    /// method is a wrapper for <see cref="GetPrefHeight()"/>, and is provided to
    /// allow calling safely from constructors.
    /// </summary>
    /// <returns> The preferred height of the textfield. </returns>
    protected float GetPrefHeightUnchecked()
    {
        float topAndBottom = 0;
        float minHeight    = 0;

        if ( _style.Background != null )
        {
            topAndBottom = Math.Max
                (
                 topAndBottom,
                 _style.Background.BottomHeight + _style.Background.TopHeight
                );
            minHeight = Math.Max( minHeight, _style.Background.MinHeight );
        }

        if ( _style.FocusedBackground != null )
        {
            topAndBottom = Math.Max
                (
                 topAndBottom,
                 _style.FocusedBackground.BottomHeight + _style.FocusedBackground.TopHeight
                );
            minHeight = Math.Max( minHeight, _style.FocusedBackground.MinHeight );
        }

        if ( _style.DisabledBackground != null )
        {
            topAndBottom = Math.Max
                (
                 topAndBottom,
                 _style.DisabledBackground.BottomHeight + _style.DisabledBackground.TopHeight
                );
            minHeight = Math.Max( minHeight, _style.DisabledBackground.MinHeight );
        }

        return Math.Max( topAndBottom + TextHeight, minHeight );
    }

    /// <summary>
    /// Get the current style of the actor
    /// </summary>
    public virtual TextFieldStyle GetStyle() => _style;

    /// <summary>
    /// Set the current style of the actor
    /// </summary>
    public virtual void SetStyle( TextFieldStyle style )
    {
        SetStyleSafe( style );
    }

    /// <summary>
    /// Sets the current style of the actor.
    /// This method is a wrapper for <see cref="SetStyleSafe(TextFieldStyle)"/>, and is
    /// provided to allow calling safely from constructors.
    /// </summary>
    /// <param name="style"> The new style to set. </param>
    protected void SetStyleSafe( TextFieldStyle style )
    {
        Guard.Against.Null( style.Font );

        _style = style;

        TextHeight = style.Font.GetCapHeight() - ( style.Font.GetDescent() * 2 );

        if ( !string.IsNullOrEmpty( Text ) )
        {
            UpdateDisplayText();
        }

        InvalidateHierarchy();
    }

    /// <summary>
    /// Calculates the render offsets and visible character range for the text in the TextField.
    /// This method ensures that the text cursor and selected text remain visible within the
    /// current viewable area of the TextField, and adjusts the rendering as needed based on the
    /// glyph positions, background, and alignment.
    /// </summary>
    public virtual void CalculateOffsets()
    {
        float           visibleWidth = GetWidth();
        ISceneDrawable? background   = GetBackgroundDrawable();

        if ( background != null )
        {
            visibleWidth -= background.LeftWidth + background.RightWidth;
        }

        int     glyphCount     = GlyphPositions.Count;
        float[] glyphPositions = GlyphPositions.ToArray();

        // Check if the cursor has gone out the left or right side of
        // the visible area and adjust renderOffset if necessary.
        float distance = glyphPositions[ Math.Max( 0, Cursor - 1 ) ] + _renderOffset;

        if ( distance <= 0 )
        {
            _renderOffset -= distance;
        }
        else
        {
            int   index = Math.Min( glyphCount - 1, Cursor + 1 );
            float minX  = glyphPositions[ index ] - visibleWidth;

            if ( -_renderOffset < minX )
            {
                _renderOffset = -minX;
            }
        }

        // Prevent renderOffset from starting too close to the end, eg after text was deleted.
        var   maxOffset = 0f;
        float width     = glyphPositions[ glyphCount - 1 ];

        for ( int i = glyphCount - 2; i >= 0; i-- )
        {
            float x = glyphPositions[ i ];

            if ( ( width - x ) > visibleWidth )
            {
                break;
            }

            maxOffset = x;
        }

        if ( -_renderOffset > maxOffset )
        {
            _renderOffset = -maxOffset;
        }

        // calculate first visible char based on render offset
        _visibleTextStart = 0;

        var startX = 0f;

        for ( var i = 0; i < glyphCount; i++ )
        {
            if ( glyphPositions[ i ] >= -_renderOffset )
            {
                _visibleTextStart = i;
                startX            = glyphPositions[ i ];

                break;
            }
        }

        // calculate last visible char based on visible width and render offset
        int   end  = _visibleTextStart + 1;
        float endX = visibleWidth - _renderOffset;

        for ( int n = Math.Min( DisplayText.Length, glyphCount ); end <= n; end++ )
        {
            if ( glyphPositions[ end ] > endX )
            {
                break;
            }
        }

        _visibleTextEnd = Math.Max( 0, end - 1 );

        if ( ( _textAlign & Align.Left ) == 0 )
        {
            TextOffset = visibleWidth - glyphPositions[ _visibleTextEnd ] - FontOffset + startX;

            if ( ( _textAlign & Align.Center ) != 0 )
            {
                TextOffset = ( float )Math.Round( TextOffset * 0.5f );
            }
        }
        else
        {
            TextOffset = startX + _renderOffset;
        }

        // calculate selection x position and width
        if ( HasSelection )
        {
            Guard.Against.Null( _style );

            int   minIndex = Math.Min( Cursor, SelectionStart );
            int   maxIndex = Math.Max( Cursor, SelectionStart );
            float minX     = Math.Max( glyphPositions[ minIndex ] - glyphPositions[ _visibleTextStart ], -TextOffset );
            float maxX = Math.Min
                (
                 glyphPositions[ maxIndex ] - glyphPositions[ _visibleTextStart ],
                 visibleWidth - TextOffset
                );

            _selectionX     = minX;
            _selectionWidth = maxX - minX - _style.Font.FontData.CursorX;
        }
    }

    /// <summary>
    /// Determines the index of the letter located under the specified x-coordinate
    /// relative to the current cursor line's glyph positions.
    /// </summary>
    /// <param name="x">The x-coordinate to check for a corresponding letter.</param>
    /// <returns>The index of the letter under the specified x-coordinate.</returns>
    protected virtual int LetterUnderCursor( float x )
    {
        x -= TextOffset + FontOffset - _style.Font.FontData.CursorX - GlyphPositions[ _visibleTextStart ];

        ISceneDrawable? background = GetBackgroundDrawable();

        if ( background != null )
        {
            x -= background.LeftWidth;
        }

        int     n              = GlyphPositions.Count;
        float[] glyphPositions = GlyphPositions.ToArray();

        for ( var i = 1; i < n; i++ )
        {
            if ( glyphPositions[ i ] > x )
            {
                if ( ( glyphPositions[ i ] - x ) <= ( x - glyphPositions[ i - 1 ] ) )
                {
                    return i;
                }

                return i - 1;
            }
        }

        return n - 1;
    }

    /// <summary>
    /// Returns <c>true</c> if the specified character is considered a word character.
    /// </summary>
    /// <param name="c">The character to check.</param>
    /// <returns><c>true</c> if the character is a word character; otherwise, <c>false</c>.</returns>
    protected virtual bool IsWordCharacter( char c )
    {
        return char.IsLetterOrDigit( c );
    }

    /// <summary>
    /// Returns the indices of the word under the cursor at the specified position.
    /// </summary>
    /// <param name="at">The position of the cursor.</param>
    /// <returns>An array containing the indices of the word under the cursor.</returns>
    protected virtual int[] WordUnderCursor( int at )
    {
        string text  = Text;
        int    right = Text.Length;
        var    left  = 0;
        int    index = at;

        if ( at >= text.Length )
        {
            left  = text.Length;
            right = 0;
        }
        else
        {
            for ( ; index < right; index++ )
            {
                if ( !IsWordCharacter( text[ index ] ) )
                {
                    right = index;

                    break;
                }
            }

            for ( index = at - 1; index > -1; index-- )
            {
                if ( !IsWordCharacter( text[ index ] ) )
                {
                    left = index + 1;

                    break;
                }
            }
        }

        return [ left, right ];
    }

    /// <summary>
    /// Retrieves the start and end indices of the word under the cursor based on
    /// the specified x-coordinate.
    /// </summary>
    /// <param name="x">
    /// The x-coordinate relative to the text field, used to determine the word under the cursor.
    /// </param>
    /// <returns>
    /// An array of two integers, where the first element represents the start index and
    /// the second element represents the end index of the word under the cursor.
    /// </returns>
    protected virtual int[] WordUnderCursor( float x )
    {
        return WordUnderCursor( LetterUnderCursor( x ) );
    }

    /// <summary>
    /// Determines whether the specified size is within the maximum allowable length.
    /// </summary>
    /// <param name="size">The size to evaluate against the maximum length.</param>
    /// <returns>
    /// <c>true</c> if the size is less than the maximum length or if no maximum length is set;
    /// otherwise, <c>false</c>.
    /// </returns>
    protected virtual bool WithinMaxLength( int size )
    {
        return ( MaxLength <= 0 ) || ( size < MaxLength );
    }

    /// <summary>
    /// Retrieves the appropriate background drawable for the TextField based on its current state.
    /// </summary>
    /// <returns>The <see cref="ISceneDrawable"/> representing the background.
    /// This could be the disabled background if the TextField is disabled,
    /// the focused background if the TextField has focus, or the default background otherwise.</returns>
    protected virtual ISceneDrawable? GetBackgroundDrawable()
    {
        if ( Disabled && ( _style.DisabledBackground != null ) )
        {
            return _style.DisabledBackground;
        }

        if ( ( _style.FocusedBackground != null ) && HasKeyboardFocus() )
        {
            return _style.FocusedBackground;
        }

        return _style.Background;
    }

    /// <inheritdoc />
    public override void Draw( IBatch batch, float parentAlpha )
    {
        bool focused = HasKeyboardFocus();

        if ( ( focused != _focused ) || ( focused && ( _blinkTask?.Status != TaskStatus.Running ) ) )
        {
            _focused = focused;
            _blink.Cancel();
            _cursorOn = focused;

            if ( focused )
            {
                _blink.Start();
            }
            else
            {
                _keyRepeat.Cancel();
            }
        }
        else if ( !focused )
        {
            _cursorOn = false;
        }

        BitmapFont font = _style.Font;

        ISceneDrawable? background = GetBackgroundDrawable();

        float x            = GetX();
        float y            = GetY();
        float width        = GetWidth();
        float height       = GetHeight();
        var   bgLeftWidth  = 0f;
        var   bgRightWidth = 0f;

        batch.SetColor( ActorColor.R, ActorColor.G, ActorColor.B, ActorColor.A * parentAlpha );

        if ( background != null )
        {
            background.Draw( batch, x, y, width, height );
            bgLeftWidth  = background.LeftWidth;
            bgRightWidth = background.RightWidth;
        }

        float textY = GetTextY( font, background );

        CalculateOffsets();

        if ( focused && HasSelection )
        {
            ISceneDrawable? selection = _style.Selection;

            if ( selection != null )
            {
                DrawSelection( selection, batch, font, x + bgLeftWidth, y + textY );
            }
        }

        float yOffset = font.Flipped ? -TextHeight : 0;

        if ( DisplayText.Length == 0 )
        {
            if ( !focused )
            {
                BitmapFont messageFont = _style.MessageFont ?? font;

                if ( _style.MessageFontColor != null )
                {
                    messageFont.SetColor
                        (
                         _style.MessageFontColor.R,
                         _style.MessageFontColor.G,
                         _style.MessageFontColor.B,
                         _style.MessageFontColor.A * ActorColor.A * parentAlpha
                        );
                }
                else
                {
                    messageFont.SetColor( Color.Gray, ActorColor.A * parentAlpha );
                }

                DrawMessageText
                    (
                     batch,
                     messageFont,
                     x + bgLeftWidth,
                     y + textY + yOffset,
                     width - bgLeftWidth - bgRightWidth
                    );
            }
        }
        else
        {
            Color? fontColor = Disabled
                                   ? _style.DisabledFontColor
                                   : focused
                                       ? _style.FocusedFontColor
                                       : _style.FontColor;

            Guard.Against.Null( fontColor ); // Or force fontColor to Color.White?

            font.SetColor( fontColor.R, fontColor.G, fontColor.B, fontColor.A * ActorColor.A * parentAlpha );
            DrawText( batch, font, x + bgLeftWidth, y + textY + yOffset );
        }

        if ( !Disabled && _cursorOn )
        {
            ISceneDrawable? cursorPatch = _style.Cursor;

            if ( cursorPatch != null )
            {
                DrawCursor( cursorPatch, batch, font, x + bgLeftWidth, y + textY );
            }
        }
    }

    /// <summary>
    /// Calculates the Y-coordinate for text rendering within the TextField,
    /// considering the font metrics and optional background drawable.
    /// </summary>
    /// <param name="font">The font used for rendering the text.</param>
    /// <param name="background">The optional background drawable that affects the placement of the text.</param>
    /// <return>The calculated Y-coordinate for rendering the text.</return>
    protected virtual float GetTextY( BitmapFont font, ISceneDrawable? background )
    {
        float height = GetHeight();
        float textY  = ( TextHeight / 2 ) + font.GetDescent();

        if ( background != null )
        {
            float bottom = background.BottomHeight;

            textY = textY + ( ( height - background.TopHeight - bottom ) / 2 ) + bottom;
        }
        else
        {
            textY += height / 2;
        }

        if ( font.GetUseIntegerPositions() )
        {
            textY = ( int )textY;
        }

        return textY;
    }

    /// <summary>
    /// Draws the selection background of the text field in the specified area.
    /// </summary>
    /// <param name="selection">The drawable object representing the selection background.</param>
    /// <param name="batch">The rendering batch used for drawing the selection.</param>
    /// <param name="font">The font used to retrieve text metrics such as descent.</param>
    /// <param name="x">
    /// The X-coordinate where the selection should be drawn, adjusted by text and font offsets.
    /// </param>
    /// <param name="y">
    /// The Y-coordinate where the selection should be drawn, adjusted by text height and font descent.
    /// </param>
    protected virtual void DrawSelection( ISceneDrawable selection, IBatch batch, BitmapFont font, float x, float y )
    {
        selection.Draw
            (
             batch,
             x + TextOffset + _selectionX + FontOffset,
             y - TextHeight - font.GetDescent(),
             _selectionWidth,
             TextHeight
            );
    }

    /// <summary>
    /// Renders the text of the TextField using the specified font and drawing batch at the given coordinates.
    /// </summary>
    /// <param name="batch">The drawing batch used for rendering the text.</param>
    /// <param name="font">The font used to render the text.</param>
    /// <param name="x">The x-coordinate for the text's position.</param>
    /// <param name="y">The y-coordinate for the text's position.</param>
    protected virtual void DrawText( IBatch batch, BitmapFont font, float x, float y )
    {
        font.Draw
            (
             batch,
             DisplayText,
             x + TextOffset,
             y,
             _visibleTextStart,
             _visibleTextEnd,
             0,
             Align.Left,
             false
            );
    }

    /// <summary>
    /// Renders the message text using the specified font and batch at the given position
    /// and within the specified maximum width.
    /// </summary>
    /// <param name="batch">The batch used to render the text.</param>
    /// <param name="font">The font used to draw the message text.</param>
    /// <param name="x">The x-coordinate at which to start drawing the text.</param>
    /// <param name="y">The y-coordinate at which to start drawing the text.</param>
    /// <param name="maxWidth">The maximum width within which the text should be drawn.</param>
    protected virtual void DrawMessageText( IBatch batch, BitmapFont font, float x, float y, float maxWidth )
    {
        font.Draw( batch, MessageText, x, y, 0, MessageText.Length, maxWidth, _textAlign, false, "..." );
    }

    /// <summary>
    /// Renders the text cursor at the specified position using the given parameters.
    /// </summary>
    /// <param name="cursorPatch">The drawable cursor representation to be rendered.</param>
    /// <param name="batch">The batch used to render the cursor.</param>
    /// <param name="font">The font associated with the text rendering in the field.</param>
    /// <param name="x">The x-coordinate where the cursor should be drawn.</param>
    /// <param name="y">The y-coordinate where the cursor should be drawn.</param>
    protected virtual void DrawCursor( ISceneDrawable cursorPatch, IBatch batch, BitmapFont font, float x, float y )
    {
        cursorPatch.Draw
            (
             batch,
             x + TextOffset + GlyphPositions[ Cursor ]
           - GlyphPositions[ _visibleTextStart ]
           + FontOffset
           + font.FontData.CursorX,
             y - TextHeight - font.GetDescent(),
             cursorPatch.MinWidth,
             TextHeight
            );
    }

    /// <summary>
    /// Updates the display text of the TextField to reflect its current content.
    /// Handles password mode, glyph validation, and layout recalculations.
    /// This method ensures that the visible text, glyph positions, and cursor/selection indexes
    /// are consistent with the TextField's internal state.
    /// </summary>
    public virtual void UpdateDisplayText()
    {
        BitmapFont     font       = _style.Font;
        BitmapFontData data       = font.FontData;
        string         text       = Text;
        int            textLength = text.Length;
        var            buffer     = new StringBuilder();

        for ( var i = 0; i < textLength; i++ )
        {
            char c = text[ i ];
            buffer.Append( data.HasGlyph( c ) ? c : ' ' );
        }

        var newDisplayText = buffer.ToString();

        if ( _passwordMode && data.HasGlyph( _passwordCharacter ) )
        {
            _passwordBuffer ??= new StringBuilder( newDisplayText.Length );

            if ( _passwordBuffer.Length > textLength )
            {
                _passwordBuffer.Length = textLength;
            }
            else
            {
                for ( int i = _passwordBuffer.Length; i < textLength; i++ )
                {
                    _passwordBuffer.Append( _passwordCharacter );
                }
            }

            DisplayText = _passwordBuffer.ToString();
        }
        else
        {
            DisplayText = newDisplayText;
        }

        GlyphLayout.SetText( font, DisplayText.Replace( '\r', ' ' ).Replace( '\n', ' ' ) );
        GlyphPositions.Clear();

        float x = 0;

        if ( GlyphLayout.Runs.Count > 0 )
        {
            GlyphLayout.GlyphRun run       = GlyphLayout.Runs.First();
            List< float >        xAdvances = run.XAdvances;

            FontOffset = xAdvances.First();

            for ( int i = 1, n = xAdvances.Count; i < n; i++ )
            {
                GlyphPositions.Add( x );
                x += xAdvances[ i ];
            }
        }
        else
        {
            FontOffset = 0;
        }

        GlyphPositions.Add( x );

        _visibleTextStart = Math.Min( _visibleTextStart, GlyphPositions.Count - 1 );
        _visibleTextEnd   = MathUtils.Clamp( _visibleTextEnd, _visibleTextStart, GlyphPositions.Count - 1 );

        if ( SelectionStart > newDisplayText.Length )
        {
            SelectionStart = textLength;
        }
    }

    /// <summary>
    /// Sets the text for this textfield.
    /// </summary>
    /// <param name="str"> The new text to be set for the TextField. </param>
    public void SetText( string? str )
    {
        str ??= string.Empty;

        if ( str.Equals( Text ) ) return;

        ClearSelection();

        string oldText = Text;
        Text = string.Empty;

        Paste( str, false );

        if ( ProgrammaticChangeEvents )
        {
            ChangeText( oldText, Text );
        }

        Cursor = 0;
    }

    /// <summary>
    /// Copies the contents of this TextField to the <see cref="IClipboard"/>
    /// implementation set on this TextField.
    /// </summary>
    public void Copy()
    {
        if ( HasSelection && !PasswordMode )
        {
            _clipboard?.Contents = Text.Substring
                (
                 Math.Min( Cursor, SelectionStart ),
                 Math.Max( Cursor, SelectionStart )
                );
        }
    }

    /// <summary>
    /// Copies the selected contents of this TextField to the <see cref="IClipboard"/>
    /// implementation set on this TextField, then removes it.
    /// </summary>
    public void Cut()
    {
        Cut( ProgrammaticChangeEvents );
    }

    /// <summary>
    /// Removes the currently selected text from the field and copies it to the clipboard.
    /// If no text is selected, the method does nothing.
    /// </summary>
    /// <param name="fireChangeEvent">
    /// Indicates whether to trigger change events after the text modification.
    /// </param>
    public void Cut( bool fireChangeEvent )
    {
        if ( HasSelection && !PasswordMode )
        {
            Copy();

            Cursor = Delete( fireChangeEvent );

            UpdateDisplayText();
        }
    }

    /// <summary>
    /// Inserts the specified content into the text field at the current cursor position or
    /// replaces the currently selected text, optionally firing a change event to notify of
    /// the content modification.
    /// </summary>
    /// <param name="content">
    /// The text to paste into the text field. If null, no action is performed.
    /// </param>
    /// <param name="fireChangeEvent">
    /// Determines whether a change event should be triggered as a result of this operation.
    /// </param>
    public void Paste( string? content, bool fireChangeEvent )
    {
        if ( content == null )
        {
            return;
        }

        var buffer     = new StringBuilder();
        int textLength = Text.Length;

        if ( HasSelection )
        {
            textLength -= Math.Abs( Cursor - SelectionStart );
        }

        Debug.Assert( _style != null, $"{nameof( _style )} != null" );

        BitmapFontData data = _style.Font.FontData;

        for ( int i = 0, n = content.Length; i < n; i++ )
        {
            if ( !WithinMaxLength( textLength + buffer.Length ) )
            {
                break;
            }

            char c = content[ i ];

            if ( !( WriteEnters && c is Newline or CarriageReturn ) )
            {
                if ( c is '\r' or '\n' )
                {
                    continue;
                }

                if ( _onlyFontChars && !data.HasGlyph( c ) )
                {
                    continue;
                }

                if ( ( Filter != null ) && !Filter.AcceptChar( this, c ) )
                {
                    continue;
                }
            }

            buffer.Append( c );
        }

        content = buffer.ToString();

        if ( HasSelection )
        {
            Cursor = Delete( fireChangeEvent );
        }

        if ( fireChangeEvent )
        {
            ChangeText( Text, Insert( Cursor, content, Text ) );
        }
        else
        {
            Text = Insert( Cursor, content, Text );
        }

        UpdateDisplayText();
        Cursor += content.Length;
    }

    /// <summary>
    /// Inserts the specified text into the given string at the specified position
    /// and returns the resulting string.
    /// </summary>
    /// <param name="position">The position in the destination string where the text should be inserted.</param>
    /// <param name="text">The text to insert into the destination string.</param>
    /// <param name="to">The destination string where the text will be inserted.</param>
    /// <returns>The resulting string after the text has been inserted.</returns>
    public string Insert( int position, string text, string to )
    {
        if ( to.Length == 0 )
        {
            return text;
        }

        return to.Substring( 0, position ) + text + to.Substring( position, to.Length );
    }

    /// <summary>
    /// Deletes the currently selected text in the TextField or the character near the
    /// cursor if no text is selected.
    /// </summary>
    /// <param name="fireChangeEvent">
    /// Indicates whether a change event should be fired after the text is modified.
    /// </param>
    /// <returns>The new cursor position after the deletion.</returns>
    public int Delete( bool fireChangeEvent )
    {
        int from     = SelectionStart;
        int to       = Cursor;
        int minIndex = Math.Min( from, to );
        int maxIndex = Math.Max( from, to );

        string newText = ( minIndex > 0 ? Text.Substring( 0, minIndex ) : string.Empty )
                       + ( maxIndex < Text.Length ? Text.Substring( maxIndex, Text.Length ) : string.Empty );

        if ( fireChangeEvent )
        {
            ChangeText( Text, newText );
        }
        else
        {
            Text = newText;
        }

        ClearSelection();

        return minIndex;
    }

    /// <summary>
    /// Sets the <see cref="Stage.GetKeyboardFocus()"/> to the next TextField. If no next
    /// text field is found, the onscreen keyboard is hidden. Does nothing if the text field
    /// is not in a stage.
    /// </summary>
    /// <param name="up">
    /// If true, the text field with the same or next smallest y coordinate is found, else
    /// the next highest.
    /// </param>
    public void Next( bool up )
    {
        if ( GetStage() == null || Parent == null )
        {
            return;
        }

        TextField current       = this;
        Vector2   currentCoords = current.Parent.LocalToStageCoordinates( _tmp2.Set( current.GetX(), current.GetY() ) );

        var stage = GetStage();

        if ( stage == null ) return;

        while ( true )
        {
            TextField? textField = current.FindNextTextField( stage.Actors, null, _tmp1, currentCoords, up );

            if ( textField == null )
            {
                // Try to wrap around.
                if ( up )
                {
                    currentCoords.Set( -float.MaxValue, -float.MaxValue );
                }
                else
                {
                    currentCoords.Set( float.MaxValue, float.MaxValue );
                }

                textField = current.FindNextTextField( stage.Actors, null, _tmp1, currentCoords, up );
            }

            if ( textField == null )
            {
                Engine.Input.SetOnscreenKeyboardVisible( false );

                break;
            }

            if ( stage.GetKeyboardFocus() == textField )
            {
                textField.SelectAll();

                break;
            }

            current = textField;
            currentCoords.Set( _tmp1 );
        }
    }

    /// <summary>
    /// Finds the next best suited <see cref="TextField"/> to focus on based on the provided parameters.
    /// </summary>
    /// <param name="actors">The list of actors to search through.</param>
    /// <param name="best">The currently identified best candidate for the next <see cref="TextField"/>.</param>
    /// <param name="bestCoords">The coordinates of the best candidate so far.</param>
    /// <param name="currentCoords">The current coordinates used for comparison.</param>
    /// <param name="up">A flag indicating the search direction. If true, searches upward; otherwise, searches downward.</param>
    /// <returns>The next best <see cref="TextField"/> to focus on, or null if no suitable candidate is found.</returns>
    private TextField? FindNextTextField( SnapshotArrayList< Actor > actors,
                                          TextField? best,
                                          Vector2 bestCoords,
                                          Vector2 currentCoords,
                                          bool up )
    {
        for ( int i = 0, n = actors.Size; i < n; i++ )
        {
            Actor actor = actors.GetAt( i );

            if ( actor is TextField textField )
            {
                if ( textField == this )
                {
                    continue;
                }

                if ( textField.Disabled || !textField.FocusTraversal || !textField.AscendantsVisible() )
                {
                    continue;
                }

                Vector2? actorCoords =
                    textField.Parent?.LocalToStageCoordinates( _tmp3.Set( textField.GetX(), textField.GetY() ) );

                if ( actorCoords is null )
                {
                    continue;
                }

                bool below = !actorCoords.Y.Equals( currentCoords.Y ) && ( ( actorCoords.Y < currentCoords.Y ) ^ up );
                bool right = actorCoords.Y.Equals( currentCoords.Y ) && ( ( actorCoords.X > currentCoords.X ) ^ up );

                if ( !below && !right )
                {
                    continue;
                }

                bool better = ( best == null )
                           || ( !actorCoords.Y.Equals( bestCoords.Y ) && ( ( actorCoords.Y > bestCoords.Y ) ^ up ) );

                if ( !better )
                {
                    better = actorCoords.Y.Equals( bestCoords.Y ) && ( ( actorCoords.X < bestCoords.X ) ^ up );
                }

                if ( better )
                {
                    best = textField;
                    bestCoords.Set( actorCoords );
                }
            }
            else if ( actor is Group group )
            {
                //TODO: Refactor to remove recursiveness 
                best = FindNextTextField( group.Children, best, bestCoords, currentCoords, up );
            }
        }

        return best;
    }

    /// <summary>
    /// Returns True if the text was changed.
    /// </summary>
    /// <param name="oldText"> The old text value before modification. </param>
    /// <param name="newText"> The new text value after modification. </param>
    private bool ChangeText( string? oldText, string? newText )
    {
        if ( ( oldText == null ) || ( newText == null ) )
        {
            return false;
        }

        if ( string.Compare( oldText, newText, StringComparison.CurrentCulture ) == 0 )
        {
            return false;
        }

        Text = newText;

        var changeEvent = PoolsMap.Obtain< ChangeListener.ChangeEvent >();

        bool cancelled = Fire( changeEvent );

        if ( cancelled )
        {
            Text = oldText;
        }

        PoolsMap.Free< ChangeListener.ChangeEvent >( changeEvent );

        return !cancelled;
    }

    /// <summary>
    /// Determines whether the cursor should continue moving based on the given index and offset.
    /// </summary>
    /// <param name="index">The current position of the cursor in the text.</param>
    /// <param name="offset">The offset to apply to the current cursor position.</param>
    /// <returns>True if the cursor should continue moving; otherwise, false.</returns>
    protected virtual bool ContinueCursor( int index, int offset )
    {
        return IsWordCharacter( Text[ index + offset ] );
    }

    /// <summary>
    /// Adjusts the position of the cursor within the text field.
    /// </summary>
    /// <param name="forward">
    /// Specifies the direction of cursor movement. If true, moves the cursor forward;
    /// otherwise, moves it backward.
    /// </param>
    /// <param name="jump">
    /// Indicates whether to skip over groups of characters (e.g., words) when moving the cursor.
    /// </param>
    protected virtual void MoveCursor( bool forward, bool jump )
    {
        int limit      = forward ? Text.Length : 0;
        int charOffset = forward ? 0 : -1;

        while ( ( forward ? ++Cursor < limit : --Cursor > limit ) && jump )
        {
            if ( !ContinueCursor( Cursor, charOffset ) )
            {
                break;
            }
        }
    }

    /// <summary>
    /// Sets the selection range in the text field based on the provided start and end indices.
    /// </summary>
    /// <param name="selectionStart">
    /// The starting index of the selection range. Must be greater than or equal to 0.
    /// </param>
    /// <param name="selectionEnd">
    /// The ending index of the selection range. Must be greater than or equal to 0.
    /// </param>
    /// <exception cref="ArgumentException">
    /// Thrown if either <paramref name="selectionStart"/> or <paramref name="selectionEnd"/>
    /// is less than 0.
    /// </exception>
    public virtual void SetSelection( int selectionStart, int selectionEnd )
    {
        if ( selectionStart < 0 )
        {
            throw new ArgumentException( "SelectionStart must be >= 0" );
        }

        if ( selectionEnd < 0 )
        {
            throw new ArgumentException( "selectionEnd must be >= 0" );
        }

        selectionStart = Math.Min( Text.Length, selectionStart );
        selectionEnd   = Math.Min( Text.Length, selectionEnd );

        if ( selectionEnd == selectionStart )
        {
            ClearSelection();

            return;
        }

        if ( selectionEnd < selectionStart )
        {
            ( selectionEnd, selectionStart ) = ( selectionStart, selectionEnd );
        }

        HasSelection   = true;
        SelectionStart = selectionStart;
        Cursor         = selectionEnd;
    }

    /// <summary>
    /// Selects all text within the TextField, extending the selection from the beginning
    /// of the text to the end. This method is used to highlight all characters
    /// for actions like copying, cutting, or replacing text.
    /// </summary>
    public void SelectAll()
    {
        SetSelection( 0, Text.Length );
    }

    /// <summary>
    /// Clears the current text selection in the TextField, if any.
    /// Sets the <see cref="HasSelection"/> property to false.
    /// </summary>
    public void ClearSelection()
    {
        HasSelection = false;
    }

    /// <summary>
    /// Sets the cursor position and clears any selection.
    /// </summary>
    public void SetCursorPosition( int cursorPosition )
    {
        if ( cursorPosition < 0 )
        {
            throw new ArgumentException( "cursorPosition must be >= 0" );
        }

        ClearSelection();

        Cursor = Math.Min( cursorPosition, Text.Length );
    }

    // ========================================================================
    // ========================================================================

    /// Manages the blinking behavior of the text cursor within a <see cref="TextField"/>.
    /// <para>
    /// This class encapsulates the logic for creating, starting, and canceling a task
    /// that controls the periodic blinking of the cursor. The task is executed asynchronously
    /// and can be managed through this class.
    /// </para>
    /// <para>
    /// Provides integration with <see cref="TextField"/> by managing the lifecycle of the
    /// blinking task. The blinking behavior is initiated by calling the <see cref="Create"/>
    /// method and starts with the <see cref="Start"/> method. The <see cref="Cancel"/> method
    /// halts the blinking process.
    /// </para>
    /// <para>
    /// Instances of this class are tied to a specific <see cref="TextField"/>, ensuring that
    /// the blinking behavior is scoped to a single text field. Improper usage or accessing
    /// methods on a disposed or canceled <see cref="BlinkTaskManager"/> instance may lead to
    /// undefined behavior.
    /// </para>
    private class BlinkTaskManager
    {
        private readonly TextField _tf;

        public BlinkTaskManager( TextField tf )
        {
            _tf = tf;
        }

        /// <summary>
        /// Creates the blinking task and initializes the cancellation token source.
        /// </summary>
        public void Create()
        {
            _tf._blinkTokenSource       = new CancellationTokenSource();
            _tf._blinkCancellationToken = _tf._blinkTokenSource.Token;

            CreateBlinkTask();
        }

        /// <summary>
        /// Handles the blinking task creation.
        /// </summary>
        private void CreateBlinkTask()
        {
            //@formatter:off
            _tf._blinkTask = new Task( () =>
               {
                   _tf._cursorOn = !_tf._cursorOn;
                   Engine.Graphics.RequestRendering();
               },
               _tf._blinkCancellationToken );
            //@formatter:on
        }

        /// <summary>
        /// Starts the blinking task.
        /// </summary>
        /// <exception cref="RuntimeException"> Thrown if the task is not created.</exception>
        public void Start()
        {
            if ( _tf is not { _blinkTask: not null } )
            {
                throw new RuntimeException( "Unable to start BlinkTask" );
            }

            _tf._blinkTask.Start();
        }

        /// <summary>
        /// Cancels the blinking task.
        /// </summary>
        public void Cancel()
        {
            if ( _tf._blinkTask is { Status: TaskStatus.Running } )
            {
                _tf._blinkTokenSource?.Cancel();
            }
        }
    }

    // ========================================================================
    // ========================================================================

    /// Manages tasks related to key repetition for a given <see cref="TextField"/>.
    /// <para>
    /// This class handles the creation, starting, and cancellation of tasks that repeat
    /// key input actions at a regular interval. It is used to implement behavior such as
    /// holding a key down and having the corresponding character input repeat continuously.
    /// </para>
    /// <para>
    /// A <see cref="KeyRepeatTaskManager"/> is associated with a single <see cref="TextField"/>
    /// and supports operations that manage the lifecycle of the key repeat task, including
    /// initialization, execution, and termination.
    /// </para>
    [PublicAPI]
    public class KeyRepeatTaskManager
    {
        public int KeyCode { get; set; }

        private readonly TextField _tf;

        public KeyRepeatTaskManager( TextField tf )
        {
            _tf = tf;
        }

        /// <summary>
        /// Handles the creation of the key repeat task.
        /// </summary>
        public void Create()
        {
            _tf._keyRepeatTokenSource       = new CancellationTokenSource();
            _tf._keyRepeatCancellationToken = _tf._keyRepeatTokenSource.Token;

            //@formatter:off
            _tf._keyRepeatTask = new Task( () =>
            {
                _tf._inputListener?.OnKeyDown( null, KeyCode );
                
                if ( _tf._keyRepeatTokenSource.IsCancellationRequested )
                {
                    _tf._keyRepeatCancellationToken.ThrowIfCancellationRequested();
                }
            },
            _tf._keyRepeatCancellationToken );
            //@formatter:on
        }

        /// <summary>
        /// Starts the key repeat task.
        /// </summary>
        /// <exception cref="RuntimeException">Thrown if the key repeat task is not initialized.</exception>
        public void Start()
        {
            if ( _tf is not { _keyRepeatTask: not null } )
            {
                throw new RuntimeException( "Unable to start KeyRepeatTask" );
            }

            _tf._keyRepeatTask.Start();
        }

        /// <summary>
        /// Cancels the key repeat task.
        /// </summary>
        public void Cancel()
        {
            if ( _tf._keyRepeatTask is { Status: TaskStatus.Running } )
            {
                _tf._keyRepeatTokenSource?.Cancel();
            }
        }
    }

    // ========================================================================
    // ========================================================================

    /// A listener class responsible for handling input events specifically for <see cref="TextField"/> widgets.
    /// <para>
    /// This class extends <see cref="ClickListener"/> and processes user interactions such as clicks, touches,
    /// and key events. It provides methods to manage the behavior of the text field when input events occur,
    /// including cursor movement, text selection, and keyboard event handling.
    /// </para>
    /// <para>
    /// It includes functionality to navigate to the start or end of a text field, position the cursor based
    /// on touch input, and handle key repeat tasks for continuous key presses. Additionally, it manages
    /// focus traversal based on typed characters.
    /// </para>
    /// <para>
    /// Designed to be used internally by <see cref="TextField"/> and its subclasses, the listener enhances
    /// interactive user experiences and ensures compatibility with the event-driven architecture of the UI framework.
    /// </para>
    [PublicAPI]
    public class TextFieldClickListener : ClickListener
    {
        private readonly TextField _tf;

        protected TextFieldClickListener()
        {
            _tf = new TextField( string.Empty, new Skin() );
        }

        protected internal TextFieldClickListener( TextField tf )
        {
            _tf = tf;
        }

        /// <inheritdoc />
        public override void OnClicked( InputEvent ev, float x, float y )
        {
            int count = TapCount % 4;

            if ( count == 0 )
            {
                _tf.ClearSelection();
            }

            if ( count == 2 )
            {
                int[] array = _tf.WordUnderCursor( x );
                _tf.SetSelection( array[ 0 ], array[ 1 ] );
            }

            if ( count == 3 )
            {
                _tf.SelectAll();
            }
        }

        /// <inheritdoc />
        public override bool OnTouchDown( InputEvent? ev, float x, float y, int pointer, int button )
        {
            if ( !base.OnTouchDown( ev, x, y, pointer, button ) )
            {
                return false;
            }

            if ( ( pointer == 0 ) && ( button != 0 ) )
            {
                return false;
            }

            if ( _tf.Disabled )
            {
                return true;
            }

            SetCursorPosition( x, y );
            _tf.SelectionStart = _tf.Cursor;

            var tfStage = _tf.GetStage();
        
            if ( tfStage != null )
            {
                tfStage.SetKeyboardFocus( _tf );
            }

            _tf._keyboard.Show( true );
            _tf.HasSelection = true;

            return true;
        }

        /// <inheritdoc />
        public override void OnTouchDragged( InputEvent? ev, float x, float y, int pointer )
        {
            base.OnTouchDragged( ev, x, y, pointer );
            SetCursorPosition( x, y );
        }

        /// <inheritdoc />
        public override void OnTouchUp( InputEvent? ev, float x, float y, int pointer, int button )
        {
            if ( _tf.SelectionStart == _tf.Cursor )
            {
                _tf.HasSelection = false;
            }

            base.OnTouchUp( ev, x, y, pointer, button );
        }

        /// <summary>
        /// Moves the cursor to the beginning of the text field.
        /// </summary>
        /// <param name="jump">
        /// Indicates whether the operation should be treated as a jump, typically for
        /// selection purposes.
        /// </param>
        protected virtual void GoHome( bool jump )
        {
            _tf.Cursor = 0;
        }

        /// <summary>
        /// Positions the cursor at the end of the text within the TextField or TextArea.
        /// </summary>
        /// <param name="jump">If true, may include additional logic for navigation behavior.</param>
        protected virtual void GoEnd( bool jump )
        {
            _tf.Cursor = _tf.Text.Length;
        }

        /// <inheritdoc />
        public override bool OnKeyDown( InputEvent? ev, int keycode )
        {
            if ( _tf.Disabled )
            {
                return false;
            }

            _tf._cursorOn = _tf._focused;
            _tf._blink.Cancel();

            if ( _tf._focused )
            {
//                Timer.schedule( _tf._blinkTask, _tf._blinkTime, _tf._blinkTime );
            }

            if ( !_tf.HasKeyboardFocus() )
            {
                return false;
            }

            var  repeat  = false;
            bool ctrl    = InputUtils.CtrlKey();
            bool jump    = ctrl && !_tf._passwordMode;
            var  handled = true;

            if ( ctrl )
            {
                switch ( keycode )
                {
                    case IInput.Keys.V:
                        _tf.Paste( _tf._clipboard?.Contents, true );
                        repeat = true;

                        break;

                    case IInput.Keys.C:
                    case IInput.Keys.Insert:
                        _tf.Copy();

                        return true;

                    case IInput.Keys.X:
                        _tf.Cut( true );

                        return true;

                    case IInput.Keys.A:
                        _tf.SelectAll();

                        return true;

                    case IInput.Keys.Z:
                        string oldText = _tf.Text;

                        _tf.SetText( _tf._undoText );
                        _tf._undoText = oldText;
                        _tf.UpdateDisplayText();

                        return true;

                    default:
                        handled = false;

                        break;
                }
            }

            if ( InputUtils.ShiftKey() )
            {
                switch ( keycode )
                {
                    case IInput.Keys.Insert:
                        _tf.Paste( _tf._clipboard?.Contents, true );

                        break;

                    case IInput.Keys.ForwardDel:
                        _tf.Cut( true );

                        break;
                }

                int temp = _tf.Cursor;

                switch ( keycode )
                {
                    case IInput.Keys.Left:
                        _tf.MoveCursor( false, jump );
                        repeat  = true;
                        handled = true;

                        break;

                    case IInput.Keys.Right:
                        _tf.MoveCursor( true, jump );
                        repeat  = true;
                        handled = true;

                        break;

                    case IInput.Keys.Home:
                        GoHome( jump );
                        handled = true;

                        break;

                    case IInput.Keys.End:
                        GoEnd( jump );
                        handled = true;

                        break;
                }

                if ( !_tf.HasSelection )
                {
                    _tf.SelectionStart = temp;
                    _tf.HasSelection   = true;
                }
            }
            else
            {
                // Cursor movement or other keys (kills selection).
                switch ( keycode )
                {
                    case IInput.Keys.Left:
                        _tf.MoveCursor( false, jump );
                        _tf.ClearSelection();
                        repeat  = true;
                        handled = true;

                        break;

                    case IInput.Keys.Right:
                        _tf.MoveCursor( true, jump );
                        _tf.ClearSelection();
                        repeat  = true;
                        handled = true;

                        break;

                    case IInput.Keys.Home:
                        GoHome( jump );
                        _tf.ClearSelection();
                        handled = true;

                        break;

                    case IInput.Keys.End:
                        GoEnd( jump );
                        _tf.ClearSelection();
                        handled = true;

                        break;
                }
            }

            _tf.Cursor = MathUtils.Clamp( _tf.Cursor, 0, _tf.Text.Length );

            if ( repeat )
            {
                ScheduleKeyRepeatTask( keycode );
            }

            return handled;
        }

        /// <inheritdoc />
        public override bool OnKeyUp( InputEvent? ev, int keycode )
        {
            if ( _tf.Disabled )
            {
                return false;
            }

            _tf._keyRepeat.Cancel();

            return true;
        }

        /// <summary>
        /// Checks if focus traversal should be triggered. The default implementation
        /// uses <see cref="TextField.FocusTraversal"/> and the typed character,
        /// depending on the OS.
        /// </summary>
        /// <param name="character"> The character that triggered a possible focus traversal. </param>
        /// <returns>
        /// true if the focus should change to the <see cref="TextField.Next(bool)"/> input field.
        /// </returns>
        protected virtual bool CheckFocusTraversal( char character )
        {
            return _tf.FocusTraversal
                && ( ( character == Tab )
                  || ( character is CarriageReturn or Newline && ( Platform.IsAndroid || Platform.IsIos ) ) );
        }

        /// <inheritdoc />
        public override bool OnKeyTyped( InputEvent? ev, char character )
        {
            if ( _tf.Disabled )
            {
                return false;
            }

            // Disallow "typing" most ASCII control characters, which would
            // show up as a space when onlyFontChars is true.
            switch ( character )
            {
                case Backspace:
                case Tab:
                case Newline:
                case CarriageReturn:
                    break;

                default:
                    if ( character < 32 )
                    {
                        return false;
                    }

                    break;
            }

            if ( !_tf.HasKeyboardFocus() )
            {
                return false;
            }

            if ( Platform.IsMac && Engine.Input.IsKeyPressed( IInput.Keys.Sym ) )
            {
                return true;
            }

            if ( CheckFocusTraversal( character ) )
            {
                _tf.Next( InputUtils.ShiftKey() );
            }
            else
            {
                bool enter     = character is CarriageReturn or Newline;
                bool delete    = character == DeleteKey;
                bool backspace = character == Backspace;

                bool add = enter
                               ? _tf.WriteEnters
                               : !_tf._onlyFontChars || _tf._style.Font.FontData.HasGlyph( character );

                bool remove = backspace || delete;

                if ( add || remove )
                {
                    string oldText   = _tf.Text;
                    int    oldCursor = _tf.Cursor;

                    if ( remove )
                    {
                        if ( _tf.HasSelection )
                        {
                            _tf.Cursor = _tf.Delete( false );
                        }
                        else
                        {
                            if ( backspace && ( _tf.Cursor > 0 ) )
                            {
                                _tf.Text = _tf.Text.Substring( 0, _tf.Cursor - 1 )
                                         + _tf.Text.Substring( _tf.Cursor-- );

                                _tf._renderOffset = 0;
                            }

                            if ( delete && ( _tf.Cursor < _tf.Text.Length ) )
                            {
                                _tf.Text = _tf.Text.Substring( 0, _tf.Cursor ) + _tf.Text.Substring( _tf.Cursor + 1 );
                            }
                        }
                    }

                    if ( add && !remove )
                    {
                        // Character may be added to the text.
                        if ( !enter && ( _tf.Filter != null ) && !_tf.Filter.AcceptChar( _tf, character ) )
                        {
                            return true;
                        }

                        if ( !_tf.WithinMaxLength
                                 (
                                  _tf.Text.Length
                                - ( _tf.HasSelection
                                        ? Math.Abs( _tf.Cursor - _tf.SelectionStart )
                                        : 0 )
                                 ) )
                        {
                            return true;
                        }

                        if ( _tf.HasSelection )
                        {
                            _tf.Cursor = _tf.Delete( false );
                        }

                        string insertion = enter ? "\n" : character.ToString();

                        _tf.Text = _tf.Insert( _tf.Cursor++, insertion, _tf.Text );
                    }

                    if ( _tf.ChangeText( oldText, _tf.Text ) )
                    {
                        long time = TimeUtils.Millis();

                        if ( ( time - 750 ) > _tf._lastChangeTime )
                        {
                            _tf._undoText = oldText;
                        }

                        _tf._lastChangeTime = time;
                        _tf.UpdateDisplayText();
                    }
                    else
                    {
                        _tf.Cursor = oldCursor;
                    }
                }
            }

            _tf.Listener?.KeyTyped( _tf, character );

            return true;
        }

        /// <summary>
        /// Sets the cursor position within the text field.
        /// </summary>
        /// <param name="x"> X coordinate. </param>
        /// <param name="y"> Y coordinate. </param>
        protected virtual void SetCursorPosition( float x, float y )
        {
            _tf.Cursor    = _tf.LetterUnderCursor( x );
            _tf._cursorOn = _tf._focused;

            _tf._blink.Cancel();

            if ( _tf._focused )
            {
//TODO:
//                Timer.Schedule( _tf._blinkTask, _tf._blinkTime, _tf._blinkTime );
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="keycode"></param>
        protected virtual void ScheduleKeyRepeatTask( int keycode )
        {
            if ( _tf._keyRepeat.KeyCode != keycode )
            {
                _tf._keyRepeat.KeyCode = keycode;
            }
        }
    }

    // ========================================================================
    // ========================================================================

    /// <summary>
    /// Interface for listening to typed characters.
    /// </summary>
    [PublicAPI]
    public interface ITextFieldListener
    {
        void KeyTyped( TextField textField, char c );
    }

    // ========================================================================
    // ========================================================================

    /// <summary>
    /// Interface for filtering characters entered into the text field.
    /// </summary>
    [PublicAPI]
    public interface ITextFieldFilter
    {
        bool AcceptChar( TextField textField, char c );

        class DigitsOnlyFilter : ITextFieldFilter
        {
            public bool AcceptChar( TextField textField, char c )
            {
                return char.IsDigit( c );
            }
        }
    }

    // ========================================================================
    // ========================================================================

    /// <summary>
    /// An interface for onscreen keyboards.
    /// Can invoke the default keyboard or render your own keyboard
    /// </summary>
    [PublicAPI]
    public interface IOnscreenKeyboard
    {
        void Show( bool visible );
    }

    // ========================================================================
    // ========================================================================

    /// <summary>
    /// The default <see cref="IOnscreenKeyboard"/> used by all {@link TextField} instances.
    /// Just uses <see cref="IInput.SetOnscreenKeyboardVisible(bool)"/> as appropriate. Might
    /// overlap your actual rendering, so use with care!
    /// </summary>
    [PublicAPI]
    public class DefaultOnscreenKeyboard : IOnscreenKeyboard
    {
        public void Show( bool visible )
        {
            Engine.Input.SetOnscreenKeyboardVisible( visible );
        }
    }
}

// ============================================================================
// ============================================================================
